- name: instalando o puppet
  package:
    name: puppetserver
    update_cache: yes
  when: ansible_hostname == "devops"

- name: instalando puppet-agent
  package:
    name: puppet-agent
    update_cache: yes

