- name: Realizando testes nos sites
  hosts: docker
  tasks:
    - name: Verificando o status do site1
      uri:
        url: http://172.2.0.2/
        method: GET
        status_code: 200

    - name: Verificando o status do site2
      uri: 
        url: http://172.2.0.3/
        method: GET
        status_code: 200
      
