- name: minha segunda playbook
  hosts: docker devops
  vars:
    username: null
    pacote: null
  tasks:
   - name: adicionar um usuario
     user:
      name: "{{ username }}"
      shell: /bin/bash
     # when: username != null
     register: condicao
     ignore_errors: yes

   - name: modulo debug
     debug:
      var: condicao

   - name: instalando um pacote
     apt:
      name: "{{ pacote }}" 
      state: present
     when: condicao.failed == false
