- name: criando um loop
  hosts: all
  tasks:
   - name: garantindo o epel-release
     yum:
      name: epel-release
     when: ansible_os_family == "RedHat"

   - name: instalacao pacotes
     package:
      name: "{{ item }}"
     with_items:
      - vim
      - cowsay
      - figlet
